import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-5">
          <Link href="/" className="text-black">
            Home
          </Link>
          <Link href="/blog" className="text-black">
            Blog
          </Link>
        </div>

        {children}
      </body>
    </html>
  );
}
