name: Migrate Staging CF to production
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Run contentful-merge create command
        id: create_migration
        run: |
          result=$(contentful-merge create --cda-token 4bRiN8wwBmbnY-GZkUO8O88sSdjIAbfX6RwE6ffUv0c --space jeqa1wtiqf6k --source staging --target master)
          echo "::set-output name=result_json::${result}"

      - name: Run contentful-merge apply command
        run: |
          contentful-merge apply --cma-token CFPAT-goBx_lH_7jF9vXxTGmuryelrvbaoHZxNQ4dwcFETSvQ --space jeqa1wtiqf6k --environment master --file ${{ steps.create_migration.outputs.result_json }}
